version: "3"
x-geoglyph-common: &geoglyph-common
  build:
    context: ../../geoglyph_composer
    dockerfile: Dockerfile
  environment: &geoglyph-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: ${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    AIRFLOW__CELERY__RESULT_BACKEND: ${AIRFLOW__CELERY__RESULT_BACKEND}
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis-geoglyph:6379/0
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
  volumes:
    - ../../geoglyph_composer:/opt/airflow
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &geoglyph-common-depends-on
    geoglyph-redis:
      condition: service_healthy

services:
  geoglyph-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
      - ./mysql/conf.d/my.cnf:/etc/mysql/my.cnf:delegated
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 33336:3306

  geoglyph-redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  geoglyph-webserver:
    <<: *geoglyph-common
    # command: webserver
    command: db init # Use fist time only
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *geoglyph-common-depends-on

  geoglyph-scheduler:
    <<: *geoglyph-common
    command: scheduler
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *geoglyph-common-depends-on

  geoglyph-triggerer:
    <<: *geoglyph-common
    command: triggerer
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *geoglyph-common-depends-on

  airflow-worker:
    <<: *geoglyph-common
    command: celery worker
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      <<: *geoglyph-common-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *geoglyph-common-depends-on
networks:
  default:
    external: true
    name: geoglyph-network
