version: "3"
services:
  geoglyph_api:
    container_name: geoglyph_api
    build:
      context: ../../geoglyph_api
      dockerfile: Dockerfile.dev
    volumes:
      - ../../geoglyph_api:/geoglyph_api
      - python-packages:/geoglyph_api/.venv
    restart: always
    depends_on:
      - geoglyph-mysql
    ports:
      - 8888:8000
    command: bash -c "uvicorn main:app --reload --host '0.0.0.0' --port 8000"
  geoglyph-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "geoglyph_develop"
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql:delegated
      - ./mysql/conf.d/my.cnf:/etc/mysql/my.cnf:delegated
    ports:
      - 33336:3306
volumes:
  python-packages:
networks:
  default:
    external: true
    name: geoglyph-network
